dataset: cifar10
image_size: 32
eval_file_prefix: CIFAR
gen_type: c_resnet
gen_path: trained_models/ResNet_G_CIFAR_SNGAN_Hinge_50000.npz
disc_type: c_sndcgan
disc_path: trained_models/DCGAN_D_CIFAR_SNGAN_NonSaturating_150001.npz
corr_type: null
corr_path: null
f_div: KL
eta: 0.1
gamma: 0.01
save_interval: 5
keep_samples: false
steps: 25
bottom_width: 4
num_imgs: 50000
batch_size: 500
exp_root: ./exps/
z_dim: 128