dataset: stl10
image_size: 48
eval_file_prefix: STL48
gen_type: c_dcgan
gen_path: trained_models/DCGAN_G_STL48_WGAN-GP_Wasserstein_150001.npz
disc_type: c_wgan
disc_path: trained_models/DCGAN_D_STL48_WGAN-GP_Wasserstein_150001.npz
corr_type: null
corr_path: null
f_div: KL
eta: 0.1
gamma: 0.01
save_interval: 5
keep_samples: true
steps: 25
bottom_width: 6
num_imgs: 50000
batch_size: 500
exp_root: ./exps/
z_dim: 128